### ISSUE TITLE
Systemd Unit File

### ISSUE THREAD

**Issue by dgalardi** [damianrath/nordvpn_randomizer-nm#1]
Hey man great script!

Any chance you could write a systemd unit file to automate it on start up?

Or is there anyway to use your script with options and arguments so it can be one shot? I might be able to try and write a systemd unit myself then.

Anyway thanks for this, I've wanted something like this for a while now but I am a total newb when it comes to this stuff.

**Comment by damianrath** [comment]
I won't be writing a systemd startup script and currently there are no command line switches available, BUT I will look into it as soon as I can.

**Comment by dgalardi** [comment]
This works perfectly.

Thank you very much
