### ISSUE TITLE
Server list update

### ISSUE THREAD

**Issue by dgalardi** [damianrath/nordvpn_randomizer-nm#2]
Would it be possible to add a switch that would download, extract, and replace list of servers with the current one?

**Comment by damianrath** [comment]
It's on my todo-list :)

**Comment by dgalardi** [comment]
Fuck yeah!

Also would it be possible to list multiple countries with the "-a|--add" switch instead of only one? Or should I make that request a separate issue?

**Comment by damianrath** [comment]
That's actually also planned for the script. I'll let you know when it's done.
